name: build-windows-exe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install LLVM (for bindgen)
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "17.0"

      - name: Build (Release)
        run: cargo build --release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: reckless-windows-exe
          path: target/release/reckless.exe
